
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: http.awx.1broken.net
  namespace: awx
spec:
  ingressClassName: nginx
  host: awx.1broken.net
  tls:
    secret: awx-tls-secret
    cert-manager:
      cluster-issuer: mcluster.1broken.net
    redirect:
      enable: false
  upstreams:
  - name: awx-demo-service
    service: awx-demo-service
    port: 80
    type: http
    tls:
      enable: false
  routes:
  - path: /
    action:
      proxy:
        upstream: awx-demo-service
